travis:
  secure:
    BINSTAR_TOKEN: TEOIR+iBP9MxFmdZGY6VC3DYBX3LLLdZXMa9GMpfrS11ba57jN9KY125uKQeahfm1ErrSPtqXHqZoTgQX5h1XzXNNe/voM6IX4sNEFx59GJEcTodtl9swd+EKJqfZmUJwaOjWUOw8XpFkcW2LkS7LrVZ7hlh9kYg0XMDfD05QJQkTfFX0hzxb/h/sazTD0yeNzFkIFqU5Zzij/whsmaOTB+6Sf3Hhvevkk2BoHsnp/igSJmLNUo0DUOcY8KT3SObKUggWTBEqjkn2p/Bc6NjUkEq34jMTuKPuaba0xEdZg9FAY5CSApjbEAMIKHWzqmsc7wfU3iYpM5D5ABPDlGE1qdB6v1hc6gSjsp0mov4qKqibGAjzeubBtLamqNsmVo3whmsQOij1FjOkw5IKjI5HuXsrx06GQkTIap+5vWvpMnaLKXyrbaSCSFJWoImpxyCOLsb5rLxUOl368GMxKStGsMMtQLX/qwsjugfMs8PGHKW4LN6U4ieBGOyB2yjvvCbUk53MOUvk32lhpILDwXxKThCl+hySnuaAkT2DQShktEQsLTFGjqFQcLTQkXGcYsaZxOtZ7u/j3dO44Cxbn6Yq8u7wZsd5khLAs2Emir9+h7wgHWSh5ESgkBRwpMko7miHIxf6UAk/tOH2hRCLt+twLI+guSOAnuDosVmJmmbmDU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
